### ISSUE TITLE
Why did we try to flag a post twice as the same user?

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/metasmoke#180]
See https://metasmoke.erwaysoftware.com/post/69717/flag_logs - somehow we tried to flag a post with the same user twice.

**Comment by Fortunate-MAN** [comment]
Same thing also happened in these posts with the same user (CalvT): [first](https://metasmoke.erwaysoftware.com/post/69631/flag_logs), [second](https://metasmoke.erwaysoftware.com/post/69632/flag_logs) and [third](https://metasmoke.erwaysoftware.com/post/69633/flag_logs).

There may be more occurrences if we dig deep enough.

**Comment by j-f1** [comment]
When looking at the Eligible Users section, I see this:
> #### Core
> CalvT
> 
> #### Everyone else

This seems to be happening because there is only 1 core user applicable, so they get used for both core and either-core-or-non-core.

**Comment by CalvT** [comment]
The errors do seem to be ramping up a bit in the past few days. 

- April 28, 1 error
- May 9, 1 error
- May 18, 1 error
- May 21, 2 errors
- May 23, 1 error
- May 24, 4 errors
- May 25, 1 error (so far)

I do have a low flagging weight, 164 at this moment. And also an account on all 167 sites.

It's possible I'm the only core member that has such a low weight on so many sites.

If you want the links to all errors from my account, let me know because I can easily get them.

**Comment by angussidney** [comment]
Note that CalvT previously had a flagging weight of 163, which is no longer possible to set since it's accuracy is too low. This would possibly explain why he was the only elegible flagger.

---

On a side note, MS only checks flagging conditions for their accuracy when the flagging condition or system settings are updated. While we could set up a cron job to disable conditions that become too inaccurate after being set up, I don't think it's worth it when they are still 99.49% accurate (threshold = 99.5%)

**Comment by CalvT** [comment]
Just to be clear, on the 2 of May, 163 gave me 99.51% accuracy. I'm not sure when it dropped to 99.49%, but think it was sometime last week.

Out of the 11 links above, 4 had a weight of 163, 6 had a weight of 167, and 1 had a weight 196

**Comment by CalvT** [comment]
Has happened twice again, [here](https://metasmoke.erwaysoftware.com/post/70388/flag_logs)(165) and [here](https://metasmoke.erwaysoftware.com/post/70136/flag_logs)(170). In the second link it first cast a flag for both me and M.A.R., then tried to cast a second one for both of us.

**Comment by ArtOfCode-** [comment]
This'll need server logs to figure out.
