### ISSUE TITLE
Review API documentation

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#226]
@ArtOfCode- [writes](/Charcoal-SE/metasmoke/issues/224#issuecomment-315864961):

> There's a bunch of undocumented routes, and another, bigger bunch of routes whose behaviour has changed or that now return extra data, all undocumented.

Review the API documentation in the wiki and update where necessary.

**Comment by sharabromberg** [comment]
the route /api/blacklist has a 500 Internal Server Error. is this route no longer used?

**Comment by NobodyNada** [comment]
@sharabromberg Looks like `BlacklistedWebsite` is undefined [here](https://github.com/Charcoal-SE/metasmoke/blob/a763523ddcd3b6bf236bab0579b38c3bedd0c684/app/controllers/api_controller.rb#L147), maybe it got renamed or something.

**Comment by NobodyNada** [comment]
Looks like you're right that that's no longer used.  MS apparently used to track blacklisted websites, but that functionality [was removed on February 4th](https://github.com/Charcoal-SE/metasmoke/commit/a2193a0a6ee6cd0182e1a521f25c63160cdd6cc7).

**Comment by j-f1** [comment]
That API route was added in [this commit](https://github.com/Charcoal-SE/metasmoke/commit/107e87d148f16428b663e2646f3d1d43da6a7a11?diff=unified#diff-7e65c41b865fef20711f630d8d14e452R56). Plus what NobodyNada said.

**Comment by sharabromberg** [comment]
sounds like this wiki page can be removed then! https://github.com/Charcoal-SE/metasmoke/wiki/Blacklisted-Websites

**Comment by sharabromberg** [comment]
if some routes now return *less* data, shall i edit the documentation to reflect these new changes?

for example: 
https://github.com/Charcoal-SE/metasmoke/wiki/Post-Reasons 
this suggests that the response will include the following data:
```
            "id":15,
            "reason_name":"Link at end of body",
            "last_post_title":"VitaPulse by Princeton Vitamins is evidently",
            "inactive":false
```

but the response actually only includes:
```
            "id":15,
            "reason_name":"Link at end of body",
```

**Comment by AWegnerGitHub** [comment]
Yes, documentation should be updated to reflect reality.

**Comment by j-f1** [comment]
…or you could update reality to reflect the documentation.

**Comment by NobodyNada** [comment]
I'm wondering if those fields are excluded by the default filter. I can't seem to figure out how to get the filters to work properly, but passing a blank filter (by appending `?filter= to the URL) causes those fields to be included.

**Comment by sharabromberg** [comment]
i've updated https://github.com/Charcoal-SE/metasmoke/wiki/Users to correctly include the moderator_sites data in the response.

**Comment by sharabromberg** [comment]
here's a spreadsheet where i'm tracking my progress, for anyone interested! https://docs.google.com/spreadsheets/d/1NhXvPyWdkGYQx2Y-poYFLgsU3plxb1zJT2zdcm44HXY/edit?usp=sharing

**Comment by sharabromberg** [comment]
So I noticed that using the Search Posts route with `site` parameter is different than using the Posts by Site route: the Search Posts route with `site` parameter (`api/posts/search?site=`) must exclude https:// from the passed value, but the Posts by Site route and parameter (`api/posts/site?site=`) must include https:// in the passed value. Otherwise, the query will not yield any results.

That's because in the api controller [`posts_by_site` uses `site_url`](https://github.com/Charcoal-SE/metasmoke/blob/a763523ddcd3b6bf236bab0579b38c3bedd0c684/app/controllers/api_controller.rb#L65), and [`search_posts` uses `site_domain`](https://github.com/Charcoal-SE/metasmoke/blob/a763523ddcd3b6bf236bab0579b38c3bedd0c684/app/controllers/api_controller.rb#L116). Is this intended, or shall I fix this?

**Comment by ArtOfCode-** [comment]
Sounds like a bug to me. You can standardise them both to `site_domain` :)

**Comment by angussidney** [comment]
@sharabromberg I've noticed that there's a few routes that you can't use since you don't have the required privileges; if you make an account on [metasmoke](https://metasmoke.erwaysoftware.com/) and tell us your username, we can give you the reviewer privilege so that you can use those routes too :)

**Comment by tripleee** [comment]
Maybe see also https://github.com/Charcoal-SE/metasmoke/issues/244

**Comment by ArtOfCode-** [comment]
API docs for v2 are up-to-date. V1 is EOL.
