### ISSUE TITLE
MS doesn't know I'm a mod

### ISSUE THREAD

**Issue by izwick-schachter** [Charcoal-SE/metasmoke#234]
Apparently it's [really bad](https://chat.stackexchange.com/transcript/message/39251089#39251089) that I'm not on the list of awesome mods [here](https://charcoal-se.org/pings/mods). I'm signed up with SE according to [this page](https://metasmoke.erwaysoftware.com/authentication/status), but not for write access.

**Comment by Undo1** [comment]
Mostly [status-bydesign], we [explicitly don't check people](https://github.com/Charcoal-SE/metasmoke/blob/master/config/schedule.rb#L17) who aren't write-authenticated (because we couldn't cast a flag as them anyway).

I've re-run the mod site check manually just to be safe, and it seems to be working as expected.

We could probably improve this by falling back to `stack_exchange_account_id` if we don't have an api_token stored.
