### ISSUE TITLE
Strange error screen

### ISSUE THREAD

**Issue by DavidPostill** [Charcoal-SE/metasmoke#31]
I was looking at the following smokey report:

https://chat.stackexchange.com/transcript/message/32617387#32617387

I clicked on the [MS] link https://m.erwaysoftware.com/posts/by-url?url=//gaming.stackexchange.com/a/286798

And the result was the following page, with some strange routing error:

![screenshot - 29_09_2016 13_49_09](https://cloud.githubusercontent.com/assets/7079224/18955091/cf44399c-864d-11e6-8d54-f428e3693238.png)

**Comment by ArtOfCode-** [comment]
That's a 404; it looks like that because we've got full error messages turned on (yes, in production, shush) for debugging purposes.

As to *why* the post didn't get created... you'd have to ask @Undo1 to look at the logs to find the point where Smokey sent the create-post request - would have been 2016-09-29T12:44Z, ish.
