### ISSUE TITLE
API route fails when passing `page` or `per_page` parameters

### ISSUE THREAD

**Issue by AWegnerGitHub** [Charcoal-SE/metasmoke#33]
I attempted to call the following URL (with a valid key):

    https://metasmoke.erwaysoftware.com/api/posts/feedback/?per_page=10&type=naa-&page=1&key=<VALIDKEY>

The goal is to get the first ten results. However, when I do so, I receive the following error:

```
ArgumentError in ApiController#posts_by_feedback 

comparison of Fixnum with String failed
Extracted source (around line #116):

114    
115    def set_pagesize
116       @pagesize = [params[:per_page] || 10, 100].min
117    end
118
119    def has_more?(page, result_count)
```

The request being sent (from that error page, is as follows - again with a valid key):

    {"per_page"=>"10", "type"=>"naa-", "page"=>"1", "key"=>"<VALIDKEY>"}

---

A similar error errors if I remove the `per_page` parameter from the URL (but leave the `page` parameter)

```
ArgumentError in ApiController#posts_by_feedback 

comparison of String with 1512 failed
	
118
119    def has_more?(page, result_count)
120        (page || 1) * @pagesize < result_count
121    end
122
123    def verify_write_token
```

The request on this call is:

    {"type"=>"naa-", "page"=>"1", "key"=>"<VALIDKEY>"}

---

If I remove both the `per_page` and `page` parameters, I receive a response, as expected

**Comment by ArtOfCode-** [comment]
This is why we test our code, kids.

I'm pretty busy over the next three days, so I may or may not have time to fix this. I know what that cause is, but I need to run some tests ideally, which I don't have the hardware to do anytime soon. @Undo1 may be able to get to it before me (hint: the solution in `has_more?` isn't a `to_i`call, because `nil || 1 == 0`, or something. It breaks things, anyway.)

**Comment by ArtOfCode-** [comment]
I may have been wrong. Both about my time and about the solution.

Sigh.
