### ISSUE TITLE
Chat IDs missing from users in the API

### ISSUE THREAD

**Issue by Glorfindel83** [Charcoal-SE/metasmoke#385]
AIM uses the chat ID to check if it needs to display 'You autoflagged':
https://github.com/Charcoal-SE/userscripts/blob/master/autoflagging/autoflagging.user.js#L202
It therefore expects the `user` object to have a `stackexchange_user_id` (or similar IDs for SOCVR and the Tavern), but those aren't exposed anymore via the API (I think it's /posts/12345/flags we're calling). The only fields that remain are `id` and `username`. I'm pretty sure the chat IDs were exposed as well, until a few days ago.

**Comment by ArtOfCode-** [comment]
Sounds like you need a [filter](https://metasmoke.erwaysoftware.com/api/filters)

**Comment by Glorfindel83** [comment]
Ah, I could be confused with the way AIM processes websocket messages, I believe they get those by default.

**Comment by Glorfindel83** [comment]
@ArtOfCode- I've created a filter with fields from the `posts` and `users` table, but it doesn't work: the [URL with filter](https://metasmoke.erwaysoftware.com/api/v2.0/posts/111546/flags?key=d897aa9f315174f081309cef13dfd7caa4ddfec1c2f8641204506636751392a4&filter=GKNJKLILHNFMJLFKINGJJHJOLGJNGL) gives the same results as the [URL without](https://metasmoke.erwaysoftware.com/api/v2.0/posts/111546/flags?key=d897aa9f315174f081309cef13dfd7caa4ddfec1c2f8641204506636751392a4).

So I'm following the advice on the filters page:

> If in doubt about which tables are available for particular routes, ask.

**Comment by ArtOfCode-** [comment]
Ah. Yeah, found the issue:

> Available tables: N/A. This route provides a specific, unfilterable subset of information.

[Source](https://charcoal-se.org/ms/API-Documentation-(V2)).

Something on the AIM side will need to call `/api/v2.0/users` as well to retrieve chat IDs.

**Comment by j-f1** [comment]
Could also change [the API method](https://github.com/Charcoal-SE/metasmoke/blob/19880085132a60472c74ab539f93bbe930781358/app/api/api/posts_api.rb#L98-L111) to use filters.

**Comment by ArtOfCode-** [comment]
PRs welcome on that, but I didn't originally because it pulls so much stuff in different aggregations from multiple tables, so a query to do the lot at once would be... complex.

**Comment by Glorfindel83** [comment]
Awwww .... more API calls? We've already multiplied the # of calls to metasmoke by 10 (all the necessary information used to be available in a single call for multiple posts)... :(

**Comment by ArtOfCode-** [comment]
Yup, and the cost of that was that V1 was fragile, hard to modify, and badly documented - and was consequently kinda difficult to use without people asking me how it worked. V2's code is much cleaner and more efficient, and it's easily documented; it's _far_ easier to use and much more of a comprehensive API. Its cost is a few more calls client-side, but I think that's a pretty fair trade-off.

The problem with V1-style all-the-information-in-one routes is illustrated very nicely here: it means the route ends up being unfilterable and far less flexible than a standard route. I am consequently loath to add more routes like that.

However, since we have one already... If we already query the chat ID information and are just transforming it out before presenting it to the client, then it won't cost anything to send it as well. I'll have a look and add it if I can.
