### ISSUE TITLE
Remove a trailing '-' from feedbacks

### ISSUE THREAD

**Issue by NobodyNada** [Charcoal-SE/metasmoke#428]
Currently, Metasmoke distinguishes between `tpu-` and `tpu`.  I don't think Metasmoke cares about the dash, but it causes e.g. multiple messages in chat since they're considered different feedbacks.  Is there a reason not to dro a trailing dash from all new feedback?

**Comment by Undo1** [comment]
We shouldn't need to drop data to accomplish this. Should be able to just check whether, e.g., we've already received *any* positive feedback before posting a chat message. Require it to be a new feedback *type*, not a new feedback *string*.

I'm pretty sure this is how it used to work, not sure when it changed.

**Comment by thesecretmaster** [comment]
Is this fixed? I don't know what the multiple messages thing is referring to, but seems to not happen anymore?

**Comment by Undo1** [comment]
@thesecretmaster 'Multiple messages' is referring to [the ones posted in chat for non-chat feedback](
https://chat.stackexchange.com/transcript/message/46709568#46709568). They *should* only be posted for the first feedback of a specific type on a post, and only if that feedback came from not-chat (API or /review).

Looks like this is still broken. Just tested it. [This message](
https://chat.stackexchange.com/transcript/message/46710389#46710389) shouldn't have been sent, because the post already had tp feedback reported in [this message](
https://chat.stackexchange.com/transcript/message/46710178#46710178).

It's apparently not irritating people enough to complain, but might be fun to investigate.
