### ISSUE TITLE
Review: NAA is a pickable option on questions

### ISSUE THREAD

**Issue by LunarWatcher** [Charcoal-SE/metasmoke#460]
![image](https://user-images.githubusercontent.com/29489988/41510896-e04103e4-726c-11e8-8f9e-8193aca0e19e.png)

The above post isn't an answer, but in review it's still possible to click NAA on it. Doing so [actually gives NAA feedback](https://chat.stackexchange.com/transcript/message/45201262#45201262). Obviously, a question isn't an answer, but the feedback option is present, and it accepts the feedback. 

Unless there's an alternative use for the NAA feedback (which there probably isn't since the [post itself](https://metasmoke.erwaysoftware.com/post/123675) doesn't have these options present), this sounds like a bug.

**Comment by thesecretmaster** [comment]
Do we want this to say "VLQ" but give naa, or what is the expected behavior here?

**Comment by Undo1** [comment]
Expected behavior is that it's not available at all - questions are far too difficult for us to be assigning quality to. There's deeper rationale for that floating around somewhere, but tl;dr is that we only really care about whether something is spam or not.

NAA feedback is a recognition that there's some stuff that's *objectively* bad (but not spam) on any site, and that we're qualified to judge that. Making calls about question quality is a whole new ball game, and one that we don't stand to profit much from.
