### ISSUE TITLE
MS fails to autoflag with "Devise could not find the Warden::Proxy instance..."

### ISSUE THREAD

**Issue by makyen** [Charcoal-SE/metasmoke#510]
This [MS post](https://m.erwaysoftware.com/posts/uid/stackoverflow/52459924) only received 1 autoflag where I'd expect it to receive 3 or 4 autoflags. The [flag logs](https://metasmoke.erwaysoftware.com/post/136374/flag_logs) indicate that an additional flag was attempted, but encountered a real error (appears to be a Rails error on MS; i.e. not just a normal SE API response), which may have resulted in no more autoflags being placed.

The error text displayed as a toolip begins with:

    Devise could not find the Warden::Proxy instance on your request environment

**Comment by ArtOfCode-** [comment]
This happens because of this line:

https://github.com/Charcoal-SE/metasmoke/blob/a82b18bdb8fc0b2be4aec770877361af4520cf5f/app/models/concerns/post_concerns/autoflagging.rb#L144

We're rendering a view manually from the controller. When you do that, Rails doesn't include the middleware stack while rendering (see [this SO answer](https://stackoverflow.com/a/39337877/3160466)), so Devise can't find a Warden instance because there isn't one.

Since these renders are just for realtime updates and the only thing we need Devise/Warden for there is an admin feature... I'm just gonna drop the link that's causing this for the realtime updates.
