### ISSUE TITLE
Some experimental reason weights haven't been correctly pinned

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#528]
Some of the new experimental reasons (`Potentially problematic ns configuration` etc) haven't been pinned to 1 reason weight yet. The list of pinned reasons needs to be updated.

The list of reasons can be found [here](https://github.com/Charcoal-SE/SmokeDetector/blob/master/globalvars.py#L64).

IIRC this requires a database edit, rather than a code edit. For that reason, I'm pinging @Undo1 

Related idea: make a web interface for pinning reason weights?

**Comment by iBug** [comment]
-1 While that reason begins with "potentially", it isn't experimental: it doesn't have a "mature" version (i.e. "potentially bad" vs "bad").

**Comment by angussidney** [comment]
@iBug Then why is it in the [experimental reasons list](https://github.com/Charcoal-SE/SmokeDetector/blob/master/globalvars.py#L75)?

**Comment by Undo1** [comment]
I pinned the three 'potentially problematic' ones for now; they looked the least stable. Up for debate on what we want to do with them (and the others on the experimental list, if there's debate there) in the long run.

**Comment by angussidney** [comment]
@iBug Sorry, I haven't expressed myself very well - in hindsight, my few words obviously weren't enough to send across the much more extensive message/opinion that I had. My bad :)

I am aware of the difference between the the two lists in terms of functionality. However, it is my understanding that they were developed in conjunction with each other, at the same time, to solve the same problem. I assumed that their purpose was one and the same - to limit the visibilty and destructive potential of any rules which are designed to catch as many TPs as possible, sometimes at the expense of a high FP rate. Thus, it was my belief that any item on one list also belonged on the other. I'm not sure whether this is still the case or not - it's quite possible that I'm out of the loop, our standards have recently changed, or there's been a misunderstanding.

Maybe it's worth having a discussion on the correct usecase for each of these features, so that we can document it and solidify it. What do we actually mean by 'exerimental'? Is that the right term for these pieces of functionality? When do we want to pin a reason to 1 reason weight? When do we want to hide it from other chatrooms? Why would you want to hide it as experimental, yet still give it the ability to contribute to autoflagging condition criteria? Or vice versa? What do we mean by a 'mature' reason? Does using 'potentially' in the name of a reason actually have any significance? Is our emerging 'heirarchy' of reasons the best way to solve the problem/usecase that it's attempting to?

There seems to be a bit of a disconnect here - personally, I don't see why an experimental reason should contribute to autoflagging weight, but you probably have an equally valid reasoning for why it should (or maybe I'm totally missing your point!). And that's ok - so maybe it's time to have a discussion to clarify some things.

Anyway, hopefully that should clear things up - sorry my response is a bit long-winded, but it's a lot better than the 9 words which I used last time to try and say the same thing :P

**Comment by iBug** [comment]
@angussidney OK I got you. Here's my understanding regarding "experimental" on both sides.

Smokey's "experimental" reasons prevents posts from being reported to other rooms (without the "experimental" rule), if the post is caught solely for "experimental". This effectively reduces noise in other rooms, as they are primarily interested in spam we caught, instead of watched items and "non-standard" "spam" checks (like the Google Perspective toxicity check).

MS's "experimental" locks the weight to 1. As the primary use of reason weights is autoflagging, the purpose of locking certain reasons to 1 is to prevent them from interfering with AF (reduce AF FP). Also, "experimental" isn't a terminology on MS that we've discussed, so it's called as-is mostly because people prefer.

Per my understanding, the two "experimental" classes weren't developed together and have somewhat different intentions. It may be worth discussing if we want an alignment, including the terminology on MS, as it's currently in a mixed state.

The reason why I objected is that "Potentially bad ns configuration" is a single-staged check. It doesn't have a 2-stage watchlist and blacklist, unlike regexes and name servers, where we (usually) watch first before promoting an item to blacklist. In fact, the check behind this reason is checking if all NS's of a domain and the domain itself are all in a single IP address, therefore "potentially problematic". So this will never become a 2-stage check.

I pick the word "mature" on my own - yeah again it's another unofficial terminology - we probably should discuss about these.
