### ISSUE TITLE
Send automatic R/A flags based on reasons?

### ISSUE THREAD

**Issue by iBug** [Charcoal-SE/metasmoke#539]
R/A flags will now disqualify posts from being picked as audits, so correctly flagging R/A has some value now.

So far MS only casts spam flags. Based on what we have, some posts are better flagged as R/A instead. A simple logic could be like this

```ruby
def should_flag_ra
  @reasons.map do |r|
    ['offensive', 'toxic', 'unique', 'repeating'].map do |s|
      r.include? s
    end.any?
  end.any?
end
```

**Comment by Undo1** [comment]
I'm gonna start this debate with "no". I'm not thrilled about the idea of spending *any* dev cycles on this, especially knowing that it'll trigger more cycles with moderators declining R/A flags on spam.

I think I'd rather take the hit on a "automated flags are always spam" policy, rather than open the door to moderators nitpicking around our conditions and us needing to respond. This would be a great reason to implement manual R/A flagging, but we already have that.

I'd be happy with a Charcoal policy of "use R/A manually when appropriate". If moderators start declining spam flags on R/A, say "it's fewer clicks for you to flag as R/A yourself than to decline flags".

Anyway, up for debate.

**Comment by thesecretmaster** [comment]
I think we should do our best to flag as what things are supposed to be. The point of the policy change was to keep R/A out of audits, by flagging as spam we're hurting that goal. Also, I believe our past policy has been that spam and R/A are equal, we just use spam because most of the stuff we flag is spam. Sure, we may flag some spam as R/A, but a) based on past policy, they're the same and b) it'll certainly be more accurate than flagging everything as spam.

**Comment by iBug** [comment]
@AWegnerGitHub Not much data needed. We have both spam (unwanted promotional content) and abusive (rudeness, garbage etc.). This is particularly about rude posts, since people don't want to see NSFW content when reviewing (audits). Given that R/A flags have their values now, IMO it's better that we send the right flags to the right posts.

**Comment by AWegnerGitHub** [comment]
> Not much data needed.

I disagree. If we are sending automatic flags, we need data. 

I understand the *reason* we want to send the correct flag. I want to see the data we have right now that can define a rude/abusive post from a spam post from an NAA post. Until I see that, I'm not going to be comfortable doing anything automatic that casts new flag types.

**Comment by ArtOfCode-** [comment]
I suspect we do have enough data to be able to classify this correctly - doing it based on reasons should be accurate enough for our purposes, given that some reasons do catch a majority of R/A not spam. That said, I have to agree with Undo - doing this opens the door to every user and their dog saying "but why isn't _this_ reason using R/A flags" or "this _combination_ of reasons"... and it all starts getting complicated. Simple systems are easier to maintain.

While @thesecretmaster is right that we shouldn't shy away from _communicating_, both with mods and with wider communities, we also don't need to open up our systems for anyone to demand a change because that's what's right in their opinion.

**Comment by magisch** [comment]
to echo @Undo1  and @ArtOfCode-  's sentiment, I don't think the added dev time for this would result in a lot of added value. 

Charcoal is already complex enough and already sort of struggles with site moderators getting comfortable with it, another layer of potential disagreement for little gain doesn't seem worth it.

**Comment by GolfingSuccess** [comment]
Tip: Mods can mark a spam flag as helpful without deleting the post, and then use R/A instead.

Given the tip above, I'm slightly leaning towards @Undo1's opinion. And what others have already said. The only con I can think of is mods deleting the post with the spam flag right away (habits).

**Comment by iBug** [comment]
Consensus: No we don't. It's complex enough and we better stay with spam flags.
