### ISSUE TITLE
Why does /spammers exist (and other stack_exchange_user strangeness)?

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#557]
When I checked today, since query logging was enabled, /spammers has one (1) hit. It lists the last 100 spammers from SO (which should be the point of /spammers/site?site=1, no?). And why is it /spammers/site?site=<id> rather than /spammers/site/:id? And why have so many of these sites not been "updated" in 1+ years? I have a feeling this stuff needs a bit of an update.

**Comment by ArtOfCode-** [comment]
Simply, it exists because it got put in when metasmoke was built, and since nobody uses it, it hasn't been updated since.

That said, I did make some changes to speed it up a bit a while back, and I reset the query counter then, so it's one hit since that point.

The by-site view is a thing intended to help moderators find spammers that haven't been destroyed on their sites yet. It uses `?site=` rather than :id so that it can be accessed via a site select dropdown. Data updates are done on request, so if sites are showing no updates recently, that's an indicator it's not getting used.

**Comment by Undo1** [comment]
Yep, this is a thing that got added because people thought autoflagging would keep spammers from being destroyed. If it's not used, I wouldn't mind shutting it off for a while and seeing if anyone notices.

**Comment by thesecretmaster** [comment]
@ArtOfCode- Could we sorta speed up /sites/dash then move this over to there? (I volunteer to do the speeding up)

**Comment by thesecretmaster** [comment]
Actually, it seems reasonably fast already (although it could be redis-ified). Maybe move the update button to the sites dashboard, setup a redirect (for old links) and then destroy the view and remove it from nav (and maybe get sites/dash into top nav).

**Comment by ArtOfCode-** [comment]
Sounds viable to me

**Comment by angussidney** [comment]
Do we even need the page at all? The per-site dashboard has a spammers tab (https://metasmoke.erwaysoftware.com/sites/dash?site_id=1&tab=spammers) which displays mostly the same information.

If for some reason we want to be able to see deleted spam accounts, you could just add a checkbox to that page that says 'show deleted'.
