### ISSUE TITLE
Nav/Homepage revisit

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#559]
I feel like it's time to take a bit of a look at this again. Some thoughts I have:

- (depending on what happens with #558) could we make the "flagging" link a flag icon and stick it over there by the search icon?
- Could we break the tools dropdown into 3 dropdowns (core, admin, dev)?
- Should /graphs move to the home page, rather than the nav? I don't think it gets much use, at least internally?
- For non-devs, should we move "status" to where the SHA is now and hide the SHA?
- Should we create a data explorers dropdown?
- Can query-times get into the nav somewhere? In a dev dropdown, if that becomes a thing?
- Does the channels email thing still exist? Where is it? Maybe if I don't know that it should be a bit more obvious :P
- The links as the bottom of the homepage are hidden. They should be easier to find. I think that if /sites/dash moves to the nav, and we agree the charcoal-se.org link is kinda useless, we can just delete that section
Also, relevant  #228

**Comment by ArtOfCode-** [comment]
Some thoughts in response to your thoughts, in order:

 - [flag icon] Could? Yes. Necessary? _shrug_
 - [3 tools dropdowns] Could? Yes. For preference, I'd leave 'em - one dropdown with dividers between the tools is just as good. Also, worth considering mobile - we don't have great mobile support, but it's good to not make it worse if we can - I don't know how this displays on mobile. Also, see below.
 - [/graphs link] Could, probably should, we should just make sure the link is reasonably prominent. Maybe keep it in the navbar for anonymous visits?
 - [status/SHA] No. Useful for everyone to be able to easily see what version we're on.
 - [data exploders] There's only two of 'em; not worth it. JS DE is kinda status-semi-supported now, too.
 - [query times] Yes. Also see below.
 - [channels email] Yes. /channels/email. Could go in the tools dropdown... see below.
 - [home links] Agree. How much use does /sites/dash see? Also depends where we put the /graphs link.

In general... we don't have great IA anywhere in metasmoke. It's a pretty flat hierarchy at the moment, and almost everything useful just gets categorised as "tools". It would be worth, rather than looking at each of these issues individually, rethinking our IA in general, trying to add some height to the hierarchy (add categories of things rather than "top level things and everything else is a tool"). This might also help solve the tools dropdown issue.

**Comment by thesecretmaster** [comment]
@ArtOfCode- Yeah, that's sorta the problem I was noticing. We just need better structure/IA.
