### ISSUE TITLE
Sites picker in flagging pages needs to be redone

### ISSUE THREAD

**Issue by Undo1** [Charcoal-SE/metasmoke#61]
The sites picker (multi-select thing) is bad. We should fix it to make it:

 1. Usable
 2. Prettier

In that order.

**Comment by ArtOfCode-** [comment]
Select2 is out; doesn't support full keyboard shortcuts on multiple selects (Ctrl-click just about works, but Shift-click and Ctrl-A don't).

**Comment by angussidney** [comment]
You could use [Bootstrap-select](https://silviomoreto.github.io/bootstrap-select/). It's a jQuery plugin that adopts the bootstrap style (number two, check), and has some useful functionality, such as:

 - A search bar - why scroll through the whole list to unselect your mod site, when you can search for it?
 - Select/deselect all
 - Supports multiple selects *without any keyboard shortcuts needed!* Just click on each item desired. (note that it doesn't support shift-select, but almost all use-cases for that I can think of are covered by the search bar and select/deselect all)
 - Placeholder value
 - Lots of other cool stuff which we don't need

(number 1, check)

I'd like to try and implement this myself so that I can get some practise at Rails.

**Comment by ArtOfCode-** [comment]
@angussidney sounds good; go for it
