### ISSUE TITLE
Clicking the feedback button twice in quick succession causes the same feedback to be added twice

### ISSUE THREAD

**Issue by gparyani** [Charcoal-SE/metasmoke#685]
I discovered that if you click a feedback button in a post record twice very rapidly in quick succession, it will register the same feedback twice for the same user. I checked the actual feedback record, and this isn't just a display bug: it's actually registered twice.

My computer has a strange glitch where it occasionally registers a mouse click twice even when I only physically click once, and so that's how I found this bug.

Can there please be a check to make sure that a single feedback cannot be registered twice, or if that's impossible, at least a scheduled task that removes duplicate feedback from the same user?

**Comment by thesecretmaster** [comment]
Is there some way we could do a multi-column unique index to enforce this? (cc @ArtOfCode- because SQL). Also, here's a handy query that shows [it almost never happens](https://metasmoke.erwaysoftware.com/data/sql/queries/207-duplicate-feedbacks). (but when it does happen, it's almost 1/3 Undo's fault :P).

**Comment by ArtOfCode-** [comment]
We _could_ index on this, yes - a unique index on post_id and feedback_type would work - but... if you click the feedback button more than once, what do you really expect to happen other than exactly this?

**Comment by user12986714** [comment]
This is probably resolved in #823 and #825.
