### ISSUE TITLE
Broken link to GraphQL Data Exploder

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#690]
The menu item in the Core menu on the metasmoke dashboard links to `/api/graphiql` but the actual functionality is on `/api/graphql` as far as I can find out.

I see a "Loading..." indicator where I would expect the site to appear, it sort of looks like it's supposed to be a redirect?

**Comment by tripleee** [comment]
@makyen says this is not the link we want. Reopening.

https://chat.stackexchange.com/transcript/message/52492944#52492944

**Comment by ArtOfCode-** [comment]
The GraphIQL interface used to work; I don't know why it doesn't now.

**Comment by makyen** [comment]
For now, I've updated the dropdown nav menu to have both a [GraphiQL link](//metasmoke.erwaysoftware.com/api/graphiql) and [GraphQL link](//metasmoke.erwaysoftware.com/api/graphql). Basically, I wanted to leave a link that's functional, but don't want to indicate that GraphiQL isn't something that should be working.

I have not tested it, but the [GraphQL link](//metasmoke.erwaysoftware.com/api/graphql) appears to lack some features which are needed to construct the spectrum of GraphQL queries.

**Comment by thesecretmaster** [comment]
Could this be because of a bundle update or something? This page comes completely from the graphql gem, so I'm not really sure why/how it broke.

**Comment by thesecretmaster** [comment]
Seems like this is the same as our problem: https://github.com/rmosolgo/graphiql-rails/issues/58

**Comment by makyen** [comment]
@thesecretmaster From reading that graphiql-rails issue, it looks like people are reporting that just restricting the graphiql-rails version to 1.4.11 will get GraphiQL working. Obviously, we'd want to track the graphiql-rails issue and remove that restriction once there's a newer version which is working again.

**Comment by thesecretmaster** [comment]
That gem also hasn't had any commits in almost the last year, so it may be unmaintained. If I'm remembering correctly, the way that our GraphQL setup works is that graphiql-rails provides the handy IDE page, but we don't depend on that for the GraphQL API as a whole (i.e. we could do without it)

**Comment by makyen** [comment]
Personally, I found what we had with GraphiQL to be quite useful. It definitely was significantly better than the alternative [here](https://metasmoke.erwaysoftware.com/api/graphql). If the older version of the graphiql-rails gem works and doesn't cause us a loss of functionality to use (e.g. it works with the separately specified/loaded GraphQL) or have security problems, then I'd prefer that we use the older version, rather than just dropping it.

If there's a better/alternate way to have the GraphiQL functionality from a maintained project, that would be better than using an older version.

[The version we were previously using was 1.5.0](https://github.com/Charcoal-SE/metasmoke/blame/a499ac4582d1abc913eda9bdb8508f3b05518729/Gemfile.lock#L206). The graphiql-rails gem version was [changed to 1.7.0](https://github.com/Charcoal-SE/metasmoke/blame/master/Gemfile.lock#L198) as an [update for most existing packages](https://github.com/Charcoal-SE/metasmoke/commit/f275f6fda7bd60eb1357babb7fe525964bd7b78a#diff-e79a60dc6b85309ae70a6ea8261eaf95). It was likely the result of a normal "update" command, rather than a targeted update to the graphiql-rails gem.

I'd suggest that we just roll it back to 1.5.0.

**Comment by tripleee** [comment]
The upstream issue looks like theirs *started* in 1.5.0 though. Maybe ours is different?

**Comment by makyen** [comment]
I [made the change to the Gemfile.lock file to have graphiql-rails on 1.5.0](https://github.com/Charcoal-SE/metasmoke/commit/1ef6112916356963e66ad938796512353a6e26eb). It looks like [it's working](https://metasmoke.erwaysoftware.com/api/graphiql). While I am seeing some errors in the browser console, I'm not sure if the errors existed previously, or not. The query I had stored on my own machine is working.

If we're comfortable with it at version 1.5.0, the Gemfile should be changed to indicate that the version is locked and the Gemfile.lock file should be regenerated.

**Comment by thesecretmaster** [comment]
Looks good to me. Thank you for testing that out!

**Comment by makyen** [comment]
It looks like this is back to not working.

**Comment by makyen** [comment]
Unfortunately, 1.4.11 isn't working either.

**Comment by makyen** [comment]
The error in the page is that the script from https://metasmoke.erwaysoftware.com/javascripts/graphiql/rails/application.js doesn't get loaded. When that URL is requested, it results in an error:

> No route matches [GET] "/javascripts/graphiql/rails/application.js"

**Comment by thesecretmaster** [comment]
Fixed in b8da74d606e2ab3ec779b4dd377c2b925fca7ebc, tl;dr the assets that this page required weren't getting precompiled in the asset pipeline.
