### ISSUE TITLE
Tag input boxes on domain pages have rendering problems

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#703]
Since this morning at least, tag input boxes on domain pages in metasmoke seem to suffer from some sort of interaction and rendering problems.

For example, https://metasmoke.erwaysoftware.com/domains/51447 has a big, wide box which does not respond to the stuff I type into it. I can type blindly and get the results I expect (for example, typing "sg" and hitting enter produces the tag "whoisguard")

The corresponding post page https://metasmoke.erwaysoftware.com/post/220628 has a perfectly rendered tag input box which responds like I expect.

**Comment by tripleee** [comment]
This isn't merely cosmetic - you cannot create new tags.

**Comment by makyen** [comment]
There's a considerable difference between the HTML which is delivered now and what the HTML used to be. Obviously, that means something changed in the HTML generation.

It's possible to apply appropriate CSS to make it functional with the current HTML/JS. However, I'd consider doing so as just a band-aid, rather than an actual fix. I'd expect we'd want to track down what changed and make a decision as to keeping the change, or not, which I'd expect to largely depend on what the change actually was.

I've pushed and deployed an update to the site's CSS which should make these dropdowns functional. I'm not closing this, as I'm assuming we want to figure out what happened to cause this change.

**Comment by tripleee** [comment]
Looking much better now, thanks.

**Comment by tripleee** [comment]
Creating a new tag still doesn't work.

**Comment by makyen** [comment]
I'm going to close this. As far as I'm aware, these are functional at this point. I had left this open in order for someone to possibly investigate the change that caused the problem, but I doubt that's going to happen at this point.
