### ISSUE TITLE
Can't remove AS tag

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/metasmoke#717]
I accidentally assigned an AS tag to a domain and now I can't remove it. Unlike regular tags, the AS ones don't have a clickable X which removes them.

**Comment by tripleee** [comment]
@makyen  managed to figure out how to remove the tag I accidentally created via a POST call. Perhaps details about how exactly should be included here for working around this bug.

**Comment by tripleee** [comment]
Seems you can also remove arbitrary tags from a domain from the post view.

**Comment by makyen** [comment]
You can also remove the "special" AS-* tags from the domain's entry in the [domain list pages](https://metasmoke.erwaysoftware.com/domains?page=9).

**Comment by thesecretmaster** [comment]
So, is the solution here to make it impossible to add or remove AS tags, so this sort of problem wouldn't happen?

**Comment by ArtOfCode-** [comment]
Better would be to make the AS tags removable

**Comment by makyen** [comment]
Well, it might be nice to just have a button on the domain page which is "fix AS tag(s)", so that any current AS tag(s) are removed and whatever appropriate AS is found from a new lookup on the domain added. This would also allow us to automatically fix the domains which never received an AS tag. There are quite a few of those, due to a now-resolved bug.

**Comment by thesecretmaster** [comment]
My fix was to 1) make it impossible to delete ASN tags but 2) add a fix asn tag button to every domain page.
