### ISSUE TITLE
Would it be beneficial to turn on branch protection for master?

### ISSUE THREAD

**Issue by thesecretmaster** [Charcoal-SE/metasmoke#748]
As mentioned in #677, it may make sense turn on branch protection now that the tests don't have sporadic failures anymore.

**Comment by teward** [comment]
How will this affect the git commits which go directly to `master` when the system does its autoblacklists, etc.?

If we are protecting a branch, we should be protecting `deploy` because we want ''bad commits' to land in master before hitting deploy.

**Comment by makyen** [comment]
It's not clear to me which options you're thinking about turning on. There are a few which you could be meaning. I'm sort-of assuming you mean turn on "Require status checks to pass before merging" and/or "Require pull request reviews before merging". To a large extent, turning on "Require status checks to pass before merging" largely will require people to go through PRs, just due to their process flow, even if "Require pull request reviews before merging" is not turned on.

Currently, a lot of the development on MS is done by directly committing to the master branch. I wouldn't want to change the configuration such that people start to think jumping through the required hoops is too much of a pain in the rear for them to contribute. Now that the tests are expected to consistently reflect the actual pass/no pass state of the code, I definitely think we should be paying more attention to the tests, and seriously considering if it's a good idea to leave a commit at the HEAD that's not passing functional testing.

So far, we've been trusting the people with write access to know what they are doing. We allow them to go ahead and commit to the master branch when the change is something they're confident in, is minor, or just needs to happen quickly. I'm more inclined to continue that level of trust/informality, than to *require* going through a PR process for every change. In general, people are choosing to go through the PR process once they feel something should be reviewed, which is a good thing.

At some point, if we see we have repeated problems with code being left as the HEAD which doesn't pass the functional testing (assuming the random errors really are gone, as we all hope), then I'd be more inclined to turn on more strict requirements.

#### A lower level of branch protection (prevent `push --force` and deletion)
SmokeDetector currently has branch protection turned on for the master branch, with no options selected. That configuration prevents forced pushes and deletion. I view that as primarily preventing mistakes. If a forced push is really needed, then an admin can temporarily turn off protection, perform the `git push --force`, then turn protection back on. Having branch protection on at that level is also a reminder that one should carefully consider the consequences and if a `--force` is really the right way to resolve the issue.

I support branch protection with a similar level of protection as SD's mater branch has for the master branch here in the MS repository (i.e. preventing `push --force` and deletion).

**Comment by teward** [comment]
I agree with Makyen, the 'lower level' of branch protection makes sense.  Nobody has direct commit access unless they know what they're doing.  (Even myself, with commit access, I never touch anything that I don't know what I'm touching).

The lower level of protection such as blocking force pushes and deletion makes more sense in my opinion.

**Comment by thesecretmaster** [comment]
Yeah, I think I concur with Makyen that we should prevent force pushes and deletions. I was basing this issue off of @ArtOfCode-'s comment [here](https://github.com/Charcoal-SE/metasmoke/issues/677#issuecomment-524109922).

**Comment by ArtOfCode-** [comment]
Concur - lower level of protection is fine

**Comment by makyen** [comment]
It appears we have a quorum that's in agreement. :)

It appears we're at the "just do it" stage. So, I've added branch protection for the master branch set to prevent `pull --force` and branch deletion.

**Comment by teward** [comment]
Since branch protection is now set on Master, I'm closing this as "Done"
