### ISSUE TITLE
Make an post age condition in the flagging conditions dialog

### ISSUE THREAD

**Issue by ferrybig** [Charcoal-SE/metasmoke#76]
At the moment, we have: Post weight, User reputation and reason count as filters.

By adding another filter called post age, we can prevent the system flagging 3 year old posts that weren't bad then, but are bad now (maybe the post was simple missed back in the days, or the website has gone bad).

**Comment by ArtOfCode-** [comment]
What real issue does this address, though?

Take the scenario of the 3-year old post which was fine when it was posted, and the website it links to has now gone bad. That's no fault of the author's; the post isn't spam, and the resolution is simply to edit the link out. So no, we shouldn't be flagging it.

However, unless it's edited, we won't even see the post. If it is edited, we won't flag it because the revision count is greater than 1.

Is there another scenario I've missed that makes this necessary?

**Comment by ferrybig** [comment]
This is mainly for the fact that if a 3 year old post suddenly received spam flags because the website it is linking is a now either a spam pattern website, or a blacklisted website (because it has gone bad now for example), we don't want the system to flag it, because the proper action would to edit the link out and allow us, humans to edit the post to either link web.archieve.org or edit the link fully out

**Comment by ArtOfCode-** [comment]
@ferrybig The post shouldn't be getting flagged in that case, though - it's not spam.
