### ISSUE TITLE
Prioritize autoflagging by activity

### ISSUE THREAD

**Issue by angussidney** [Charcoal-SE/metasmoke#79]
(originally posted by @magisch here: https://github.com/Charcoal-SE/SmokeDetector/issues/457)

> In preparation for when we're casting more then 1 auto flag, it would be nice to use flags from people who aren't currently active first in autoflagging (so the people who are active can use their manual flags on top of the auto flags).
> For that, I propose basing it on feedback and autoflags.
> Create a priority list, and people who haven't feedbacked a post or been made to autoflag a post for the longest will be prioritized.

Comment by @tripleee: 
> Maybe this should be a user preference. At least initially, I would like to be able to see what the system is doing in my name.

**Comment by markyi370** [comment]
Personally, I think that it doesn't really matter. Any user is capable of flagging.

**Comment by j-f1** [comment]
There could be a setting for hours when you’re able to flag, so that the autoflagging would skip you then.

**Comment by Undo1** [comment]
I've thought about that, but this is the issue:

![screen shot 2017-02-14 at 9 51 44 am](https://cloud.githubusercontent.com/assets/5162342/22939214/393a6ca4-f29b-11e6-8b5e-265a6e240555.png)

Since spam, and especially autoflag-able spam, is highly concentrated within an ~7hr window, I'm not sure what the use case for having a timing selection would be - mostly, you're either sleeping or you're not during that window.

**Comment by magisch** [comment]
@Undo1 People go to meetings or have busy days - a lot in fact. Activity per reviewer varies even across usual "Busy windows".

**Comment by ArtOfCode-** [comment]
Are the current core-reserved flags enough for this, or should we still look at prioritising by least-recently-active if possible?

**Comment by Undo1** [comment]
I'd vote that the current system is good enough. It'll all even out over large enough numbers.

**Comment by magisch** [comment]
@Undo1  @ArtOfCode-  Yeah I think the current system is fine.
