### ISSUE TITLE
automatic depreciation for website and keyword blacklistings

### ISSUE THREAD

**Issue by magisch** [Charcoal-SE/metasmoke#81]
I think that any website or keyword that was blacklisted but hasn't seen a single true positive in over a year should be removed from the blacklist. 

As @ArtOfCode-  noted to me in chat, the extensive blacklist has a performance hit, and since spammers discard domains like they do feces, there really isn't a reason to keep a 1 year old website blacklist entry in our databases.

These removed entries should of course not be removed from the calculation that calculates post scores, maybe they should just be moved to a separate file?

Anyways, I propose the automatic removal of lines in the blacklisted_websites.txt and bad_keywords.txt files which meet the following conditions:

- They haven't caught a single TP in 1 year
- They've been around at least 1 1/2 years

Wasn't sure whether to post this FR here or on the SD repo, since it has components for both, but move/recreate as appropriate please.

**Comment by angussidney** [comment]
It's your lucky day! I've already started work on something to do this: https://github.com/Charcoal-SE/blacklist-audits. Currently, it is a little bit broken because I am yet to convert the fully-featured Python regexes to work with Metasmoke's limited syntax, but it works. 

The current checks are: last TP was over 1 year ago, accuracy <50%. 

Currently it only recommends items to be removed, it doesn't actually do anything about it. However, once I finish getting it working, we could implement it as an automated task on the MS Server so we don't have to do a thing.

**Comment by ArtOfCode-** [comment]
Gonna close this one, since it's almost certainly out of scope for metasmoke. It'll be something to do with another project.
