### ISSUE TITLE
Incorrect domain TP/FP/NAA count in some posts

### ISSUE THREAD

**Issue by double-beep** [Charcoal-SE/metasmoke#810]
In some posts, the domain count is incorrect. For example, here is what I see to every [`surveymonkey.com`](https://metasmoke.erwaysoftware.com/domains/17908) post:

![image](https://user-images.githubusercontent.com/38133098/92926871-5d180f00-f445-11ea-9f6c-cbf3f446dcb6.png)

**Comment by makyen** [comment]
Another example:
- [What are the use cases for Apache Spark vs Hadoop](https://metasmoke.erwaysoftware.com/post/254801) and the domain [perfectial.com](https://metasmoke.erwaysoftware.com/domains/18249), which is showing "perfectial.com (0, 0, 0)", but the domain is (7, 5, 2)

**Comment by tripleee** [comment]
https://metasmoke.erwaysoftware.com/post/252287 displays (0, 0, 0) for [bytemart.org](https://metasmoke.erwaysoftware.com/domains/60755), should be (1, 0, 0).

**Comment by makyen** [comment]
At this point, I'm unable to duplicate the issue which was reported in the initial comment. It's possible that it's still occurring, but the linked examples don't show the issue for me.

The issue which @tripleee mentions is different than what's reported in the initial comment here. The issue @tripleee  reports is that when the TP/FP/NAA results for the domain are displayed on a post's page, the counts do not include the currently viewed post. This appears to be intentional, as the database queries very explicitly remove the current post. I'm not sure what the purpose is of doing it that way. I, also, find it confusing that the count for the current post is excluded from the displayed counts and would prefer that not to be the case. 

Related: PR #896 
That PR will change the behavior such that the counts of the current post are not removed from the displayed values (i.e. it will resolve the issue mentioned above by @tripleee).

**Comment by makyen** [comment]
I'm going to close this. At this point, I'm no longer able to duplicate the originally reported issue on any of the posts which have been linked here or in other related issues.

The issue which [@tripleee reported on 2021-09-13](https://github.com/Charcoal-SE/metasmoke/issues/810#issuecomment-918841863) has been resolved by the merge of #896.
