### ISSUE TITLE
Autoflagging conditions for specific reasons 

### ISSUE THREAD

**Issue by Daniil-M-beep** [Charcoal-SE/metasmoke#814]
Can we have additional autoflagging configurations for specific reasons? i.e. I wouldn't mind an autoflag if one of the reasons was 100-weight no matter the weight or other reasons.

**Comment by ArtOfCode-** [comment]
Declining. The system is the way it is because that's the easiest way to make it work for any use case and still be certain that it's functioning sufficiently accurately; in other words, because it specifically avoids having to write in exceptions and accuracy checks for multiple different possible scenarios.
