### ISSUE TITLE
Autoflags button blocked on mobile (or small window size)

### ISSUE THREAD

**Issue by CoconutMacaroon** [Charcoal-SE/metasmoke#939]
With a small window size, the button to view automatically-cast-flags is blocked so I can't click it:
![image](https://user-images.githubusercontent.com/45187468/185670401-99399519-df7d-4f4a-bf9a-7510ad19115f.png)

**Comment by makyen** [comment]
Yeah, moving the "flagging" and "search" buttons out of the topbar and down to the upper-left was, IMO, non-optimal and created multiple situations where they cover content at lower screen widths. Overall, what's needed here is to adjust the topbar such that it handles a variety of screen widths, with at least consideration for: wide (where everything fits), mid widths (which these were moved out of the topbar to accommodate), and narrow (which is handled by putting the topbar buttons in a waffle menu, but which excludes these, because they were moved out of the topbar).

**Comment by makyen** [comment]
This was resolved by moving the search and flagging selections back into the topbar.
